### PR TITLE
feat: extract notice file content

### LINKED ISSUE #937: Also NOTICE text should be included in the output
Hi,

I'd like to use this plugin to comply with a bunch libraries licenses that I include in my webapp bundle. But I noticed that the `NOTICE` file text is not included in the output although, from what I understand, it is a requirement of some licenses such as `Apache 2.0`. 

https://www.apache.org/licenses/LICENSE-2.0.txt  4.d
> If the Work includes a "NOTICE" text file as part of its
          distribution, then any Derivative Works that You distribute must
          include a readable copy of the attribution notices contained
          within such NOTICE file, excluding those notices that do not
          pertain to any part of the Derivative Works, in at least one
          of the following places: within a NOTICE text file distributed
          as part of the Derivative Works; within the Source form or
          documentation, if provided along with the Derivative Works; or,
          within a display generated by the Derivative Works, if and
          wherever such third-party notices normally appear. The contents
          of the NOTICE file are for informational purposes only and
          do not modify the License. You may add Your own attribution
          notices within Derivative Works that You distribute, alongside
          or as an addendum to the NOTICE text from the Work, provided
          that such additional attribution notices cannot be construed
          as modifying the License.

Do you think this feature could be added? I could also work on it and open a PR (I've never worked on a webpack plugin, but I can give it a try)

### PR DESCRIPTION
**Pull request by ccatterina**
Closes #937

### CODE REVIEW

**Comment by ccatterina** [comment]
Hi @codepunkt , what do you think? Should I include a dependency with a notice file in the e2e test?

**Comment by codepunkt** [comment]
@ccatterina First of all, thanks a lot!

> Hi @codepunkt , what do you think? Should I include a dependency with a notice file in the e2e test?

That'd be lovely 😄

**Comment by ccatterina** [comment]
@codepunkt 
I've added `mathjs` to the e2e example.  It has some other dependencies that are added to the package, unfortunately I have not found other npm packages with the NOTICE file and without dependencies.

**Comment by codepunkt** [comment]
@ccatterina I'm sorry that my reaction to your PR took this long.

You did a great job, feel free to add yourself to the list of contributors in `package.json` in another PR! 😀

I've made the notice file inclusion optional, via `includeNoticeText` option (defaults to `false`).
I also decided to remove notice file extraction from e2e tests since it slowed them down on my local machine from 10 to ~35 seconds and made them run into timeouts when running them on GitHub actions. I think full unit test coverage for this feature is good enough.

**Comment by codepunkt** [comment]
Released with v`4.5.0`

**Comment by ccatterina** [comment]
> @ccatterina I'm sorry that my reaction to your PR took this long.
> 
> You did a great job, feel free to add yourself to the list of contributors in `package.json` in another PR! 😀
> 
> I've made the notice file inclusion optional, via `includeNoticeText` option (defaults to `false`). I also decided to remove notice file extraction from e2e tests since it slowed them down on my local machine from 10 to ~35 seconds and made them run into timeouts when running them on GitHub actions. I think full unit test coverage for this feature is good enough.

no problem! and thank you for merging the PR! :slightly_smiling_face:

**Pull request merged**
